export let partsList= [
  {
    label: "总成/零件代码-名称:",
    value: "XMGL-XQWD-01-2019需求变更整理与分析",
    readonly: true,
    type: "",
  },
  {
    label: "输出物名称:",
    value: "需求分析文档",
    readonly: true,
    type: "",
  },
  {
    label: "所属项目:",
    value: "日常工作-软件开发部（2019）",
    readonly: true,
    type: "",
  },
  {
    label: "里程碑:",
    value: "软件部工作（1-12月）",
    readonly: true,
    type: "",
  },
  {
    label: "阶段:",
    value: "1月-3月",
    readonly: true,
    type: "",
  },
  {
    label: "工作时间:",
    value: "自 2019-02-14  至 2019-02-21",
    readonly: true,
    type: "",
  },
  {
    label: "工期（标准工时）:",
    value: "7天",
    readonly: true,
    type: "",
  },
  {
    label: "工作地点:",
    value: "吉安",
    readonly: true,
    type: "",
  },
  {
    label: "状态:",
    value: "审核中",
    readonly: true,
    type: "",
  },
  {
    label: "总消耗工时:",
    value: "4.0  天",
    readonly: true,
    type: "",
  },
  {
    label: "完成率:",
    value: "90%",
    readonly: true,
    type: "",
  },
  {
    label: "占比:",
    value: "25%",
    readonly: true,
    type: "",
  },
  {
    label: "工作人员:",
    value: "张珊",
    readonly: true,
    type: "",
  },
]